In [83]:
import pandas as pd
import numpy as np

pokemon_db = pd.read_csv("Pokemon.csv")

pokemon_db.head(50)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False
10,8,Wartortle,Water,NaN,405,59,63,80,65,80,58,1,False
11,9,Blastoise,Water,NaN,530,79,83,100,85,105,78,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False
13,10,Caterpie,Bug,NaN,195,45,30,35,20,20,45,1,False
14,11,Metapod,Bug,NaN,205,50,20,55,25,25,30,1,False
15,12,Butterfree,Bug,Flying,395,60,45,50,90,80,70,1,False
16,13,Weedle,Bug,Poison,195,40,35,30,20,20,50,1,False
17,14,Kakuna,Bug,Poison,205,45,25,50,25,25,35,1,False
18,15,Beedrill,Bug,Poison,395,65,90,40,45,80,75,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False
20,16,Pidgey,Normal,Flying,251,40,45,40,35,35,56,1,False
21,17,Pidgeotto,Normal,Flying,349,63,60,55,50,50,71,1,False
22,18,Pidgeot,Normal,Flying,479,83,80,75,70,70,101,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,579,83,80,80,135,80,121,1,False
24,19,Rattata,Normal,NaN,253,30,56,35,25,35,72,1,False
25,20,Raticate,Normal,NaN,413,55,81,60,50,70,97,1,False
26,21,Spearow,Normal,Flying,262,40,60,30,31,31,70,1,False
27,22,Fearow,Normal,Flying,442,65,90,65,61,61,100,1,False
28,23,Ekans,Poison,NaN,288,35,60,44,40,54,55,1,False
29,24,Arbok,Poison,NaN,438,60,85,69,65,79,80,1,False
30,25,Pikachu,Electric,NaN,320,35,55,40,50,50,90,1,False
31,26,Raichu,Electric,NaN,485,60,90,55,90,80,110,1,False
32,27,Sandshrew,Ground,NaN,300,50,75,85,20,30,40,1,False
33,28,Sandslash,Ground,NaN,450,75,100,110,45,55,65,1,False
34,29,Nidoran♀,Poison,NaN,275,55,47,52,40,40,41,1,False
35,30,Nidorina,Poison,NaN,365,70,62,67,55,55,56,1,False
36,31,Nidoqueen,Poison,Ground,505,90,92,87,75,85,76,1,False
37,32,Nidoran♂,Poison,NaN,273,46,57,40,40,40,50,1,False
38,33,Nidorino,Poison,NaN,365,61,72,57,55,55,65,1,False
39,34,Nidoking,Poison,Ground,505,81,102,77,85,75,85,1,False
40,35,Clefairy,Fairy,NaN,323,70,45,48,60,65,35,1,False
41,36,Clefable,Fairy,NaN,483,95,70,73,95,90,60,1,False
42,37,Vulpix,Fire,NaN,299,38,41,40,50,65,65,1,False
43,38,Ninetales,Fire,NaN,505,73,76,75,81,100,100,1,False
44,39,Jigglypuff,Normal,Fairy,270,115,45,20,45,25,20,1,False
45,40,Wigglytuff,Normal,Fairy,435,140,70,45,85,50,45,1,False
46,41,Zubat,Poison,Flying,245,40,45,35,30,40,55,1,False
47,42,Golbat,Poison,Flying,455,75,80,70,65,75,90,1,False
48,43,Oddish,Grass,Poison,320,45,50,55,75,65,30,1,False
49,44,Gloom,Grass,Poison,395,60,65,70,85,75,40,1,False

In [84]:
pokemon_db[['Name','HP','Attack']]

                      Name  HP  Attack
0                Bulbasaur  45      49
1                  Ivysaur  60      62
2                 Venusaur  80      82
3    VenusaurMega Venusaur  80     100
4               Charmander  39      52
..                     ...  ..     ...
795                Diancie  50     100
796    DiancieMega Diancie  50     160
797    HoopaHoopa Confined  80     110
798     HoopaHoopa Unbound  80     160
799              Volcanion  80     110

[800 rows x 3 columns]

In [85]:
pokemon_db[['Name','Type 1','Speed']]

                      Name   Type 1  Speed
0                Bulbasaur    Grass     45
1                  Ivysaur    Grass     60
2                 Venusaur    Grass     80
3    VenusaurMega Venusaur    Grass     80
4               Charmander     Fire     65
..                     ...      ...    ...
795                Diancie     Rock     50
796    DiancieMega Diancie     Rock    110
797    HoopaHoopa Confined  Psychic     70
798     HoopaHoopa Unbound  Psychic     80
799              Volcanion     Fire     70

[800 rows x 3 columns]

In [86]:
pokemon_db.isnull().sum()
pokemon_db["HP"].mean()

np.float64(69.25875)

In [87]:
pokemon_db.groupby('Type 1')['Attack'].mean().sort_values(ascending=False)

Type 1
Dragon      112.125000
Fighting     96.777778
Ground       95.750000
Rock         92.863636
Steel        92.703704
Dark         88.387097
Fire         84.769231
Flying       78.750000
Poison       74.678571
Water        74.151786
Ghost        73.781250
Normal       73.469388
Grass        73.214286
Ice          72.750000
Psychic      71.456140
Bug          70.971014
Electric     69.090909
Fairy        61.529412
Name: Attack, dtype: float64

In [88]:
pokemon_db.loc[64, ["Type 1","Type 2","Name"]]
pokemon_db.iloc[50:60, 0:6]

     #       Name  Type 1  Type 2  Total  HP
50  45  Vileplume   Grass  Poison    490  75
51  46      Paras     Bug   Grass    285  35
52  47   Parasect     Bug   Grass    405  60
53  48    Venonat     Bug  Poison    305  60
54  49   Venomoth     Bug  Poison    450  70
55  50    Diglett  Ground     NaN    265  10
56  51    Dugtrio  Ground     NaN    405  35
57  52     Meowth  Normal     NaN    290  40
58  53    Persian  Normal     NaN    440  65
59  54    Psyduck   Water     NaN    320  50

In [89]:
pokemon_db[pokemon_db["Type 1"] == 'Electric']

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
30,25,Pikachu,Electric,NaN,320,35,55,40,50,50,90,1,False
31,26,Raichu,Electric,NaN,485,60,90,55,90,80,110,1,False
88,81,Magnemite,Electric,Steel,325,25,35,70,95,55,45,1,False
89,82,Magneton,Electric,Steel,465,50,60,95,120,70,70,1,False
108,100,Voltorb,Electric,NaN,330,40,30,50,55,55,100,1,False
109,101,Electrode,Electric,NaN,480,60,50,70,80,80,140,1,False
134,125,Electabuzz,Electric,NaN,490,65,83,57,95,85,105,1,False
146,135,Jolteon,Electric,NaN,525,65,65,60,110,95,130,1,False
157,145,Zapdos,Electric,Flying,580,90,90,85,125,90,100,1,True
186,172,Pichu,Electric,NaN,205,20,40,15,35,35,60,2,False
193,179,Mareep,Electric,NaN,280,55,40,40,65,45,35,2,False
194,180,Flaaffy,Electric,NaN,365,70,55,55,80,60,45,2,False
195,181,Ampharos,Electric,NaN,510,90,75,85,115,90,55,2,False
196,181,AmpharosMega Ampharos,Electric,Dragon,610,90,95,105,165,110,45,2,False
258,239,Elekid,Electric,NaN,360,45,63,37,65,55,95,2,False
262,243,Raikou,Electric,NaN,580,90,85,75,115,100,115,2,True
337,309,Electrike,Electric,NaN,295,40,45,40,65,40,65,3,False
338,310,Manectric,Electric,NaN,475,70,75,60,105,60,105,3,False
339,310,ManectricMega Manectric,Electric,NaN,575,70,75,80,135,80,135,3,False
340,311,Plusle,Electric,NaN,405,60,50,40,85,75,95,3,False
341,312,Minun,Electric,NaN,405,60,40,50,75,85,95,3,False
448,403,Shinx,Electric,NaN,263,45,65,34,40,34,45,4,False
449,404,Luxio,Electric,NaN,363,60,85,49,60,49,60,4,False
450,405,Luxray,Electric,NaN,523,80,120,79,95,79,70,4,False
464,417,Pachirisu,Electric,NaN,405,60,45,70,45,90,95,4,False
513,462,Magnezone,Electric,Steel,535,70,70,115,130,90,60,4,False
517,466,Electivire,Electric,NaN,540,75,123,67,95,85,95,4,False
531,479,Rotom,Electric,Ghost,440,50,50,77,95,77,91,4,False
532,479,RotomHeat Rotom,Electric,Fire,520,50,65,107,105,107,86,4,False
533,479,RotomWash Rotom,Electric,Water,520,50,65,107,105,107,86,4,False
534,479,RotomFrost Rotom,Electric,Ice,520,50,65,107,105,107,86,4,False
535,479,RotomFan Rotom,Electric,Flying,520,50,65,107,105,107,86,4,False
536,479,RotomMow Rotom,Electric,Grass,520,50,65,107,105,107,86,4,False
581,522,Blitzle,Electric,NaN,295,45,60,32,50,32,76,5,False
582,523,Zebstrika,Electric,NaN,497,75,100,63,80,63,116,5,False
648,587,Emolga,Electric,Flying,428,55,75,60,75,60,103,5,False
663,602,Tynamo,Electric,NaN,275,35,55,40,45,40,60,5,False
664,603,Eelektrik,Electric,NaN,405,65,85,70,75,70,40,5,False
665,604,Eelektross,Electric,NaN,515,85,115,80,105,80,50,5,False
704,642,ThundurusIncarnate Forme,Electric,Flying,580,79,115,70,125,80,111,5,True
705,642,ThundurusTherian Forme,Electric,Flying,580,79,105,70,145,80,101,5,True
764,694,Helioptile,Electric,Normal,289,44,38,33,61,43,70,6,False
765,695,Heliolisk,Electric,Normal,481,62,55,52,109,94,109,6,False
772,702,Dedenne,Electric,Fairy,431,67,58,57,81,67,101,6,False

In [92]:
pokemon_db[(pokemon_db["Speed"] > 100) & (pokemon_db["Type 1"] == 'Water')| (pokemon_db["Type 2"] == 'Water')]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
130,121,Starmie,Water,Psychic,520,60,75,85,100,85,115,1,False
149,138,Omanyte,Rock,Water,355,35,40,100,90,55,35,1,False
150,139,Omastar,Rock,Water,495,70,60,125,115,70,55,1,False
151,140,Kabuto,Rock,Water,355,30,80,90,55,45,55,1,False
152,141,Kabutops,Rock,Water,495,60,115,105,65,70,80,1,False
307,283,Surskit,Bug,Water,269,40,30,32,50,52,65,3,False
349,319,SharpedoMega Sharpedo,Water,Dark,560,70,140,70,110,65,105,3,False
398,363,Spheal,Ice,Water,290,70,40,50,55,50,25,3,False
399,364,Sealeo,Ice,Water,410,90,60,70,75,70,45,3,False
400,365,Walrein,Ice,Water,530,110,80,90,95,90,65,3,False
445,400,Bibarel,Normal,Water,410,79,85,60,55,60,71,4,False
466,419,Floatzel,Water,NaN,495,85,105,55,85,50,115,4,False
533,479,RotomWash Rotom,Electric,Water,520,50,65,107,105,107,86,4,False
575,516,Simipour,Water,NaN,498,75,98,63,98,63,101,5,False
713,647,KeldeoOrdinary Forme,Water,Fighting,580,91,72,90,129,90,108,5,False
714,647,KeldeoResolute Forme,Water,Fighting,580,91,72,90,129,90,108,5,False
726,658,Greninja,Water,Dark,530,72,95,67,103,71,122,6,False
758,688,Binacle,Rock,Water,306,42,52,67,39,56,50,6,False
759,689,Barbaracle,Rock,Water,500,72,105,115,54,86,68,6,False
760,690,Skrelp,Poison,Water,320,50,60,60,60,60,30,6,False
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True